##
## Aporeto
##
[[constraint]]
  name = "github.com/aporeto-inc/trireme-lib"
  version = "^8.0.0"

[[override]]
  name = "github.com/bvandewalle/go-ipset"
  revision = "0ee897a6d8bc6095299e9c03293ece091ef871de"

##
## 3rd Party
##
[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "^1.5.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/client-go"
  version = "^7.0.0"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "e386b2658ed20923da8cc9250e552f082899a1ee"

##
## Prunes
##
[prune]
  go-tests = true
  unused-packages = true
